[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "classad"
author = "Eileen Kuehn, Max Fischer"
author-email = "mainekuehn@gmail.com"
classifiers = ["License :: OSI Approved :: MIT License"]

